### ISSUE TITLE
(Question) Why 14.7456 mhz? (Will 16MHz likely work as well?)

### ISSUE THREAD

**Issue by wyatt8740** [jtsiomb/a500kbd#5]
Sorry, this isn't really an issue as much as a question from someone dumb (me).
Is there any reason why 14.7456 MHz was chosen for this project? Was it just "I happened to have that crystal handy" or is it a good match for the speed of the keyboard bus?

I ask this because I'm wondering if there is there anything you can think of that would make this work worse at 16mhz, which would let me just program an Arduino (ATMega328P) with a 16 MHz crystal that I've got lying around with an ISP and not have to scavenge for any parts. I'm not very knowledgeable about the Amigas, having only gotten my first a couple years ago and only gotten to work on it in the last few months. I'll enjoy being able to use it with my Model M.

**Comment by jtsiomb** [comment]
Please in the future send questions through email. This is for bug reports.

The reason for the specific crystal value, is that it divides nicely into standard UART rates like the 9600 baud I'm using for the debug serial port. Using frequencies like 16MHz would introduce transmission errors in this case. There's a nice table in the AVR atmega datasheet which shows the error rate for various different frequencies.

For the arduino I assume this isn't an issue, since you can use the USB serial port for this, but I never actually used an arduino so I'm not sure. In any case, this is just for debugging purposes, and it shouldn't affect the operation of the controller in any way.

**Comment by wyatt8740** [comment]
My bad. Thanks for the quick reply. Some people hate getting email so I'm never sure.

That makes sense; on the Uno there's a separate AVR as a 'serial-to-USB-packets' chip (like an FTDI chip). I probably could get away with 16mhz, then. Sorry again about using the wrong channel of communication. Thanks, I'll try it next weekend.
